openapi: 3.0.0
info:
  title: Bike It
  description: API para um serviço hipotético de gerenciamento de um cicle
  version: 0.1
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
paths:
  /users:
    get:
      tags:
        - user
      summary: Returns a list of users
      operationId: getUsers
      responses:
        '200':
          description: A JSON array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/401Unauthorized'
    post:
      tags:
        - user
      summary: Create a new user
      operationId: addUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: user
          in: body
          description: The user JSON to be added
          schema:
            $ref: '#/components/schemas/User'
          required: true
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
              description: New resource's URL
        '400':
          description: Content invalid.
        '401':
          $ref: '#/components/responses/401Unauthorized'
  /users/{userId}:
    get:
      tags:
        - user
      summary: Returns an user
      operationId: getUserById
      responses:
        '200':
          description: A JSON of user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: The specified user ID is invalid (not a number).
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
    put:
      tags:
        - user
      summary: Update an user
      operationId: updateUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: user
          in: body
          description: The user JSON to be updated
          schema:
            $ref: '#/components/schemas/User'
          required: true
      responses:
        '200':
          description: A JSON of user updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
    delete:
      tags:
        - user
      summary: Deletes an user
      operationId: deleteUser
      responses:
        '204':
          description: Success
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
  /users/{userId}/services:
    get:
      tags:
        - user
      summary: Returns a service array of a user
      operationId: getServicesByUserId
      responses:
        '200':
          description: A JSON array of services
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
        '400':
          description: The specified user ID is invalid (not a number).
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
  /stores:
    get:
      tags:
        - store
      summary: Returns a list of stores
      operationId: getStores
      responses:
        '200':
          description: A JSON array of stores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Store'
        '401':
          $ref: '#/components/responses/401Unauthorized'
    post:
      tags:
        - store
      summary: Create a new store
      operationId: addStore
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: store
          in: body
          description: The store JSON to be added
          schema:
            $ref: '#/components/schemas/Store'
          required: true
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
              description: New resource's URL
        '400':
          description: Content invalid.
        '401':
          $ref: '#/components/responses/401Unauthorized'
  /stores/{storeId}:
    get:
      tags:
        - store
      summary: Returns an store
      operationId: getStoreById
      responses:
        '200':
          description: A JSON of store
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Store'
        '400':
          description: The specified store ID is invalid (not a number).
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
    put:
      tags:
        - store
      summary: Update an store
      operationId: updateStore
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: store
          in: body
          description: The store JSON to be updated
          schema:
            $ref: '#/components/schemas/Store'
          required: true
      responses:
        '200':
          description: A JSON of store updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Store'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
    delete:
      tags:
        - store
      summary: Deletes an store
      operationId: deleteStore
      responses:
        '204':
          description: Success
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
  /stores/{storeId}/services:
    get:
      tags:
        - store
      summary: Returns an service array
      operationId: getServicesByUserId
      responses:
        '200':
          description: A JSON array of services
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
        '400':
          description: The specified user ID is invalid (not a number).
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
  /staffs:
    get:
      tags:
        - staff
      summary: Returns a list of staff
      operationId: getUsers
      responses:
        '200':
          description: A JSON array of staff
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Staff'
        '401':
          $ref: '#/components/responses/401Unauthorized'
    post:
      tags:
        - staff
      summary: Create a new staff
      operationId: addStaff
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: staff
          in: body
          description: The staff JSON to be added
          schema:
            $ref: '#/components/schemas/Staff'
          required: true
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
              description: New resource's URL
        '400':
          description: Content invalid.
        '401':
          $ref: '#/components/responses/401Unauthorized'
  /staffs/{staffId}:
    get:
      tags:
        - staff
      summary: Returns a staff
      operationId: getStaffById
      responses:
        '200':
          description: A JSON of staff
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Staff'
        '400':
          description: The specified staff ID is invalid (not a number).
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
    put:
      tags:
        - staff
      summary: Update an staff
      operationId: updateStaff
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: staff
          in: body
          description: The store JSON to be updated
          schema:
            $ref: '#/components/schemas/Staff'
          required: true
      responses:
        '200':
          description: A JSON of staff updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Staff'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
    delete:
      tags:
        - staff
      summary: Deletes an staff
      operationId: deleteStaff
      responses:
        '204':
          description: Success
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
  /staffs/{staffId}/services:
    get:
      tags:
        - staff
      summary: Returns an service array
      operationId: getServicesByStaffId
      responses:
        '200':
          description: A JSON array of service
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
        '400':
          description: The specified user ID is invalid (not a number).
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
  /services:
    get:
      tags:
        - service
      summary: Returns a list of services
      operationId: getServices
      responses:
        '200':
          description: A JSON array of services
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Services'
        '401':
          $ref: '#/components/responses/401Unauthorized'
    post:
      tags:
        - service
      summary: Create a new service
      operationId: addService
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: service
          in: body
          description: The service JSON to be added
          schema:
            $ref: '#/components/schemas/Service'
          required: true
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
              description: New resource's URL
        '400':
          description: Content invalid.
        '401':
          $ref: '#/components/responses/401Unauthorized'
  /services/{serviceId}:
    get:
      tags:
        - service
      summary: Returns a service
      operationId: getServiceById
      responses:
        '200':
          description: A JSON of service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        '400':
          description: The specified service ID is invalid (not a number).
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
    put:
      tags:
        - service
      summary: Update an staff
      operationId: updateStaff
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: service
          in: body
          description: The service JSON to be updated
          schema:
            $ref: '#/components/schemas/Service'
          required: true
      responses:
        '200':
          description: A JSON of service updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
    delete:
      tags:
        - service
      summary: Deletes a service
      operationId: deleteService
      responses:
        '204':
          description: Success
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'

components:
  #-------------------
  # Reusable responses
  #-------------------
  responses:
    404NotFound:        # Can be referenced as '#/components/responses/404NotFound'
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    401Unauthorized:    # Can be referenced as '#/components/responses/401Unauthorized'
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      
  #-------------------------------
  # Reusable schemas (data models)
  #-------------------------------
  schemas:
    User:               # Can be referenced as '#/components/schemas/User'
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - id
        - name
    Service:            # Can be referenced as '#/components/schemas/Service'
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        userId:
          type: integer
          format: int64
      required:
        - id
        - name
        - userId
    Staff:              # Can be referenced as '#/components/schemas/Staff'
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - id
        - name
    Store:              # Can be referenced as '#/components/schemas/Store'
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - id
        - name
    Error:              # Can be referenced as '#/components/schemas/Error'
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
          
  #-------------------------------
  # Reusable operation parameters
  #-------------------------------
  parameters:
    offsetParam:        # Can be referenced as '#/components/parameters/offsetParam'
      name: offset
      in: query
      description: Number of items to skip before returning the responses.
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0
        
    limitParam:         # Can be referenced as '#/components/parameters/limitParam'
      name: limit
      in: query
      description: Maximum number of items to return.
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        default: 20
        
